- name: Copy consul-ui.hcl
  template:
    src: consul-ui.hcl.j2
    dest: /etc/consul.d/consul-ui.hcl
  notify: Restart Consul
  become: yes

- name: Consul template configuration file
  template:
    src: consul.hcl.j2
    dest: /etc/consul.d/consul.hcl
    owner: consul
    group: consul
  notify: Restart Consul
  become: yes
