---
#tasks file for nomad
- name: Set cron job for dynamic dns
  include_tasks: cloudns-cron.yml
  
- name: Download Nomad
  include_tasks: nomad-download.yml

- name: Configure Docker
  include_tasks: configure-docker.yml

- name: Configure Nomad
  include_tasks: configure-nomad.yml

- name: Nomad Job
  include_tasks: nomad-job.yml

- name: Configure Keycloak
  include_tasks: configure-keycloak.yml