- name: Add Nomad apt key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
  become: yes

- name: Add Nomad repository
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
  become: yes

- name: Install Nomad
  apt:
    pkg:
    - nomad
    - python3-pip
    update_cache: yes
  become: yes
