name: CREATE_ENV

on:
  push:
    branches: [ "bcirh-patch-1" ]
  workflow_dispatch:

jobs:
  terraform-provision:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Run terraform version
        run: terraform --version

      - name: Run terraform init
        run: terraform -chdir=terraform init

      - name: Run terraform plan
        env: 
          TF_VAR_SUBSCRIPTION_ID: ${{ secrets.TF_VAR_SUBSCRIPTION_ID }}
          TF_VAR_TENANT_ID: ${{ secrets.TF_VAR_TENANT_ID }}
          TF_VAR_CLIENT_SECRET: ${{ secrets.TF_VAR_CLIENT_SECRET }}
          TF_VAR_CLIENT_ID: ${{ secrets.TF_VAR_CLIENT_ID }}
        run: terraform -chdir=terraform plan
