name: CREATE_ENV

on:
  push:
    branches: [ "bcirh-patch-1" ]
  workflow_dispatch:

jobs:
  terraform-provision:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Run terraform version
        run: terraform --version

      - name: Run terraform init
        run: terraform -chdir=terraform init

      - name: Run terraform plan
        env: 
          subid: ${{ secrets.TF_VAR_SUBSCRIPTION_ID }}
          tenant_id: ${{ secrets.TF_VAR_TENANT_ID }}
          secret: ${{ secrets.TF_VAR_CLIENT_SECRET }}
          appId: ${{ secrets.TF_VAR_CLIENT_ID }}
        run: terraform -chdir=terraform -var="subscription_id=$(subid)" -var="client_id=$(appId)" -var="client_secret=$(secret) -var=tenant_id=$(tenant_id)" plan
