name: CREATE_ENV

on:
  push:
    branches: [ "bcirh-patch-1" ]
  workflow_dispatch:

jobs:
  terraform-provision:
    runs-on: ubuntu-22.04
    env:
      TF_VAR_subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
      TF_VAR_client_id: ${{ secrets.CLIENT_ID }}
      TF_VAR_client_secret: ${{ secrets.CLIENT_SECRET }}
      TF_VAR_tenant_id: ${{ secrets.TENANT_ID }}
    steps:
      - uses: actions/checkout@v4

      - name: List env vars
        run: env

      - name: Run terraform version
        run: terraform --version

      - name: Run terraform init
        run: terraform -chdir=terraform init

      - name: Run terraform plan
        run: terraform -chdir=terraform plan
