name: CREATE_ENV

on:
  push:
    branches: [ "bcirh-patch-1" ]
  workflow_dispatch:

jobs:
  terraform-provision:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Run terraform version
        run: terraform --version

      - name: Run terraform plan
        run: terraform -chdir=terraform plan
